GOOS=android    GOARCH=arm      go build -o bin/jprq-android-arm        jprq_cli/client/*.go
GOOS=darwin     GOARCH=amd64    go build -o bin/jprq-darwin-amd64       jprq_cli/client/*.go
GOOS=darwin     GOARCH=arm64    go build -o bin/jprq-darwin-arm64       jprq_cli/client/*.go
GOOS=dragonfly  GOARCH=amd64    go build -o bin/jprq-dragonfly-amd64    jprq_cli/client/*.go
GOOS=freebsd    GOARCH=386      go build -o bin/jprq-freebsd-386        jprq_cli/client/*.go
GOOS=freebsd    GOARCH=amd64    go build -o bin/jprq-freebsd-amd64      jprq_cli/client/*.go
GOOS=freebsd    GOARCH=arm      go build -o bin/jprq-freebsd-arm        jprq_cli/client/*.go
GOOS=linux      GOARCH=386      go build -o bin/jprq-linux-386          jprq_cli/client/*.go
GOOS=linux      GOARCH=amd64    go build -o bin/jprq-linux-amd64        jprq_cli/client/*.go
GOOS=linux      GOARCH=arm      go build -o bin/jprq-linux-arm          jprq_cli/client/*.go
GOOS=linux      GOARCH=arm64    go build -o bin/jprq-linux-arm64        jprq_cli/client/*.go
GOOS=linux      GOARCH=ppc64    go build -o bin/jprq-linux-ppc64        jprq_cli/client/*.go
GOOS=linux      GOARCH=ppc64le  go build -o bin/jprq-linux-ppc64le      jprq_cli/client/*.go
GOOS=linux      GOARCH=mips     go build -o bin/jprq-linux-mips         jprq_cli/client/*.go
GOOS=linux      GOARCH=mipsle   go build -o bin/jprq-linux-mipsle       jprq_cli/client/*.go
GOOS=linux      GOARCH=mips64   go build -o bin/jprq-linux-mips64       jprq_cli/client/*.go
GOOS=linux      GOARCH=mips64le go build -o bin/jprq-linux-mips64le     jprq_cli/client/*.go
GOOS=netbsd     GOARCH=386      go build -o bin/jprq-netbsd-386         jprq_cli/client/*.go
GOOS=netbsd     GOARCH=amd64    go build -o bin/jprq-netbsd-amd64       jprq_cli/client/*.go
GOOS=netbsd     GOARCH=arm      go build -o bin/jprq-netbsd-arm         jprq_cli/client/*.go
GOOS=openbsd    GOARCH=386      go build -o bin/jprq-openbsd-386        jprq_cli/client/*.go
GOOS=openbsd    GOARCH=amd64    go build -o bin/jprq-openbsd-amd64      jprq_cli/client/*.go
GOOS=openbsd    GOARCH=arm      go build -o bin/jprq-openbsd-arm        jprq_cli/client/*.go
GOOS=plan9      GOARCH=386      go build -o bin/jprq-plan9-386          jprq_cli/client/*.go
GOOS=plan9      GOARCH=amd64    go build -o bin/jprq-plan9-amd64        jprq_cli/client/*.go
GOOS=solaris    GOARCH=amd64    go build -o bin/jprq-solaris-amd64      jprq_cli/client/*.go
GOOS=windows    GOARCH=386      go build -o bin/jprq-windows-386.exe    jprq_cli/client/*.go
GOOS=windows    GOARCH=amd64    go build -o bin/jprq-windows-amd64.exe  jprq_cli/client/*.go
