GOOS=darwin     GOARCH=amd64    go build -o bin/jprq-darwin-amd64       cli/*.go
GOOS=darwin     GOARCH=arm64    go build -o bin/jprq-darwin-arm64       cli/*.go
GOOS=linux      GOARCH=386      go build -o bin/jprq-linux-386          cli/*.go
GOOS=linux      GOARCH=amd64    go build -o bin/jprq-linux-amd64        cli/*.go
GOOS=linux      GOARCH=arm      go build -o bin/jprq-linux-arm          cli/*.go
GOOS=linux      GOARCH=arm64    go build -o bin/jprq-linux-arm64        cli/*.go
GOOS=linux      GOARCH=ppc64    go build -o bin/jprq-linux-ppc64        cli/*.go
GOOS=linux      GOARCH=ppc64le  go build -o bin/jprq-linux-ppc64le      cli/*.go
GOOS=linux      GOARCH=mips     go build -o bin/jprq-linux-mips         cli/*.go
GOOS=linux      GOARCH=mipsle   go build -o bin/jprq-linux-mipsle       cli/*.go
GOOS=linux      GOARCH=mips64   go build -o bin/jprq-linux-mips64       cli/*.go
GOOS=linux      GOARCH=mips64le go build -o bin/jprq-linux-mips64le     cli/*.go
GOOS=windows    GOARCH=386      go build -o bin/jprq-windows-386.exe    cli/*.go
GOOS=windows    GOARCH=amd64    go build -o bin/jprq-windows-amd64.exe  cli/*.go